// <auto-generated />
using System;
using EcommerceAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307055421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcommerceAPI.Models.DayResume", b =>
                {
                    b.Property<int>("DayResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DayResumeId"));

                    b.Property<decimal>("CardValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Delivered")
                        .HasColumnType("int");

                    b.Property<decimal>("DollarNetValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DollarWithdrawal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Expense")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FacebookExpense")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossRenevue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MonthResumeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RealNetValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RealWithdrawal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Return")
                        .HasColumnType("int");

                    b.Property<decimal>("WithdrawalExpense")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DayResumeId");

                    b.HasIndex("MonthResumeId");

                    b.ToTable("Day_Resume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.MonthResume", b =>
                {
                    b.Property<int>("MonthResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MonthResumeId"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MonthResumeId");

                    b.ToTable("Month_Resume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DropiId")
                        .HasColumnType("int");

                    b.Property<int>("MonthResumeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ShopifyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SupplierValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("MonthResumeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EcommerceAPI.Models.DayResume", b =>
                {
                    b.HasOne("EcommerceAPI.Models.MonthResume", "DayMonthResume")
                        .WithMany("MonthDaysResume")
                        .HasForeignKey("MonthResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayMonthResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.HasOne("EcommerceAPI.Models.MonthResume", "OrderMonthResume")
                        .WithMany("MonthOrders")
                        .HasForeignKey("MonthResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderMonthResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.MonthResume", b =>
                {
                    b.Navigation("MonthDaysResume");

                    b.Navigation("MonthOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
