// <auto-generated />
using System;
using EcommerceAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcommerceAPI.Models.DayResume", b =>
                {
                    b.Property<int>("DayResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DayResumeId"));

                    b.Property<float>("CardValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DayMonthResumeMonthResumeId")
                        .HasColumnType("int");

                    b.Property<int>("Delivered")
                        .HasColumnType("int");

                    b.Property<float>("DollarNetValue")
                        .HasColumnType("float");

                    b.Property<float>("DollarWithdrawal")
                        .HasColumnType("float");

                    b.Property<float>("Expense")
                        .HasColumnType("float");

                    b.Property<float>("FacebookExpense")
                        .HasColumnType("float");

                    b.Property<float>("GrossRenevue")
                        .HasColumnType("float");

                    b.Property<float>("RealNetValue")
                        .HasColumnType("float");

                    b.Property<float>("RealWithdrawal")
                        .HasColumnType("float");

                    b.Property<int>("Return")
                        .HasColumnType("int");

                    b.Property<float>("WithdrawalExpense")
                        .HasColumnType("float");

                    b.HasKey("DayResumeId");

                    b.HasIndex("DayMonthResumeMonthResumeId");

                    b.ToTable("DaysResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.MonthResume", b =>
                {
                    b.Property<int>("MonthResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MonthResumeId"));

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MonthResumeId");

                    b.ToTable("MonthsResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DropiId")
                        .HasColumnType("int");

                    b.Property<float>("NetValue")
                        .HasColumnType("float");

                    b.Property<int?>("OrderMonthResumeMonthResumeId")
                        .HasColumnType("int");

                    b.Property<float>("ShippingValue")
                        .HasColumnType("float");

                    b.Property<int>("ShopifyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SupplierValue")
                        .HasColumnType("float");

                    b.Property<float>("TotalValue")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderMonthResumeMonthResumeId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceAPI.Models.DayResume", b =>
                {
                    b.HasOne("EcommerceAPI.Models.MonthResume", "DayMonthResume")
                        .WithMany("MonthDaysResume")
                        .HasForeignKey("DayMonthResumeMonthResumeId");

                    b.Navigation("DayMonthResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Order", b =>
                {
                    b.HasOne("EcommerceAPI.Models.MonthResume", "OrderMonthResume")
                        .WithMany("MonthOrders")
                        .HasForeignKey("OrderMonthResumeMonthResumeId");

                    b.Navigation("OrderMonthResume");
                });

            modelBuilder.Entity("EcommerceAPI.Models.MonthResume", b =>
                {
                    b.Navigation("MonthDaysResume");

                    b.Navigation("MonthOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
